/* CVS $Id: MODELDIFF.java,v 1.5 2006/09/07 08:17:23 rebach Exp $ */
package org.wymiwyg.rdf.molecules.diff.vocabulary; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/rdf-utils/rdf/model-diff.rdf 
 * @author Auto-generated by schemagen on 20 Mar 2006 19:14 
 */
public class MODELDIFF {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://wymiwyg.org/ontologies/diff#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Indicates a document which has the subject as primary-topic by being either 
     *  a serialized rdf graph or a folder containing exactly two such files, one 
     *  for each model in the diff.</p>
     */
    public static final Property functionallyGroundedIn = m_model.createProperty( "http://wymiwyg.org/ontologies/diff#functionallyGroundedIn" );
    
    /** <p>The name of a resource, this property is assigned after anonymizing a named 
     *  resource</p>
     */
    public static final Property name = m_model.createProperty( "http://wymiwyg.org/ontologies/diff#name" );
    
}
