/* CVS $Id: MOLECULESTORE.java,v 1.3 2006/09/07 08:17:23 rebach Exp $ */
package org.wymiwyg.rdf.molecules.diff.vocabulary; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from /home/reto/workspace/rdf-utils/rdf/molecule-store.rdf 
 * @author Auto-generated by schemagen on 20 Mar 2006 19:14 
 */
public class MOLECULESTORE {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://wymiwyg.org/ontologies/molecule-store#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The source of an assertion, typically an agent or a newsfeed.</p> */
    public static final Property asserter = m_model.createProperty( "http://wymiwyg.org/ontologies/molecule-store#asserter" );
    
    /** <p>the moment at which an assertion was made</p> */
    public static final Property moment = m_model.createProperty( "http://wymiwyg.org/ontologies/molecule-store#moment" );
    
    /** <p>A gaph asserted with an assertion</p> */
    public static final Property assertedComponent = m_model.createProperty( "http://wymiwyg.org/ontologies/molecule-store#assertedComponent" );
    
    /** <p>The act of asserting a graph at a determined point in time</p> */
    public static final Resource Assertion = m_model.createResource( "http://wymiwyg.org/ontologies/molecule-store#Assertion" );
    
    /** <p>An RDF Graph</p> */
    public static final Resource Graph = m_model.createResource( "http://wymiwyg.org/ontologies/molecule-store#Graph" );
    
    /** <p>A terminal molecule</p> */
    public static final Resource TerminalMolecule = m_model.createResource( "http://wymiwyg.org/ontologies/molecule-store#TerminalMolecule" );
    
    /** <p>A contextual molecule</p> */
    public static final Resource ContextualMolecule = m_model.createResource( "http://wymiwyg.org/ontologies/molecule-store#ContextualMolecule" );
    
    /** <p>A functionally grounded node</p> */
    public static final Resource FunctionallyGroundedNode = m_model.createResource( "http://wymiwyg.org/ontologies/molecule-store#FunctionallyGroundedNode" );
    
}
